CREATE TABLE `manifestations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`weekOf` datetime NOT NULL,
	`spiritualRating` int,
	`socialRating` int,
	`relationshipRating` int,
	`statusRating` int,
	`teamRating` int,
	`businessRating` int,
	`travelRating` int,
	`environmentRating` int,
	`familyRating` int,
	`skillsRating` int,
	`healthRating` int,
	`affirmationsRating` int,
	`spiritualCurrentState` text,
	`socialCurrentState` text,
	`relationshipCurrentState` text,
	`statusCurrentState` text,
	`teamCurrentState` text,
	`businessCurrentState` text,
	`travelCurrentState` text,
	`environmentCurrentState` text,
	`familyCurrentState` text,
	`skillsCurrentState` text,
	`healthCurrentState` text,
	`affirmationsCurrentState` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `manifestations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `weekly_plannings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`weekOf` datetime NOT NULL,
	`companyWide` text,
	`marketing` text,
	`sales` text,
	`churn` text,
	`creatives` text,
	`dsp` text,
	`finance` text,
	`recruiting` text,
	`systems` text,
	`fulfilment` text,
	`pendingRoadmap` text,
	`eaTasks` text,
	`paTasks` text,
	`personalTasks` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `weekly_plannings_id` PRIMARY KEY(`id`)
);
